python-interpreter-path = "C:/Users/kumbh/AppData/Local/Programs/Python/Python313/python.exe"

search-path = [
    "..",
    ".",
    "C:/Users/kumbh/AppData/Local/Programs/Python/Python313/Lib/site-packages",
    "C:/Users/kumbh/AppData/Roaming/Python/Python313/site-packages",
    "../.venv/Lib/site-packages"
]
